services:
  db:
    image: postgres:13
    container_name: whensat-db
    environment:
      POSTGRES_DB: ws
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: whensat-api/Dockerfile
    container_name: whensat-api
    ports:
      - "4444:4444"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/ws
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - LIQUIBASE_CONTEXTS=prod
    depends_on:
      - db

volumes:
  postgres_data:
